[build]
target = "riscv32ec-unknown-eabi.json"
rustflags = [
    "-C",
    "linker=riscv64-unknown-elf-gcc",
    "-C",
    "link-arg=-Wl,-Tmemory.x",
    "-C",
    "link-arg=-Wl,-Tlink.x",
    "-C",
    "link-arg=-nostartfiles",
]

[target.riscv32ec-unknown-eabi]
runner = "./run-sim.sh"

[target.riscv32emc-unknown-eabi]
runner = "./run-sim.sh"

[target.riscv32ic-unknown-eabi]
runner = "./run-sim.sh"

[target.riscv32ic-unknown-none-elf]
runner = "./run-sim.sh"

[target.riscv32imc-unknown-eabi]
runner = "./run-sim.sh"

[target.riscv32imc-unknown-none-elf]
runner = "./run-sim.sh"

[unstable]
build-std = ["core"]
