[unstable]
build-std = ["core"]

[target.riscv32ec-unknown-none-elf]
rustflags = [
    "-C",
    "linker=riscv64-unknown-elf-gcc",
    "-C",
    "link-arg=-Wl,-Tmemory.x",
    "-C",
    "link-arg=-Wl,-Tlink.x",
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-march=rv32ec",
    "-C",
    "link-arg=-mabi=ilp32e",
]
runner = "./tulitikli.sh"

[target.riscv32ic-unknown-none-elf]
rustflags = [
    "-C",
    "linker=riscv64-unknown-elf-gcc",
    "-C",
    "link-arg=-Wl,-Tmemory.x",
    "-C",
    "link-arg=-Wl,-Tlink.x",
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-march=rv32ic",
    "-C",
    "link-arg=-mabi=ilp32",
]
runner = "./tulitikli.sh"
